name: Build MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: build-MacOS-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # Install boost
      - name: Install boost
        run: |
          brew install boost
      # Build and test in debug mode
      - name: Build debug
        run: |
          mkdir -p build-debug
          cd build-debug
          CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j
      - name: Test debug
        run: |
          cd build-debug
          make test
      # Build and test in release mode
      - name: Build release
        run: |
          mkdir -p build-release
          cd build-release
          CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j
      - name: Test release
        run: |
          cd build-release
          make test
